print("Iam glad you are back!")
print("now we will learn some advanced words")
print("these words are a bit difficult but you can do it")
print("good luck!")
print("famiglia - family")
print("amico - friend")
print("scuola - school")
print("lavoro - work")
print("città - city")
print("paese - country")
print("libro - book")
print("cibo - food")
print("acqua - water")
print("tempo - time")
print("giorno - day")
print("notte - night")
print("settimana - week")
print("mese - month")
print("anno - year")
print("oggi - today")
print("domani - tomorrow")
print("I hope you done well")
print("In the next lesson we will learn some phrases")
print("be ready till then")
print("goodbye!")