print("welcome to basic sentences")
print("let's learn some basic sentences in italian")
print("good luck!")
print("come ti chiami? - what is your name?")
print("mi chiamo... - my name is...")
print("di dove sei? - where are you from?")
print("sono di... - I am from...")
print("quanti anni hai? - how old are you?")
print("ho ... anni - I am ... years old")
print("parli inglese? - do you speak english?")
print("si, parlo inglese - yes, I speak english")
print("no, non parlo inglese - no, I don't speak english")
print("non capisco - I don't understand")
print("puoi aiutarmi? - can you help me?")
print("You have completed basic sentences")
print("In the next lesson we will learn some intermidiate sentences")
print("be ready till then")
print("goodbye!")