print("Hello - Ciao")
print("Goodbye - Arrivederci")
print("Please - Per favore")
print("Thank you - Grazie")
print("Yes - Sì")
print("No - No")
print("Excuse me - Mi scusi")
print("Do you have any questions?")
question = input()
print("Thank you for your question: " + question)
print("We will get back to you soon!")
print("Goodbye")