print("want to learn more?")
print("lets start with intermidiate words")
print("they are not very easy but you can do it")
print("I hope you have fun learning italian")
print("good luck")
print("tutto bene - all good")
print("come stai? - how are you?")
print("sto bene - I am good")
print("mi chiamo... - my name is...")
print("piacere di conoscerti - nice to meet you")
print("dove - where")
print("quando - when")
print("perché - why")
print("chi - who")
print("come - how")
print("quanto costa? - how much does it cost?")
print("aiuto! - help!")
print("buon appetito - enjoy your meal")
print("that's all for now")
print("In the next lesson we will learn some advanced words")
print("be ready till then")
print("goodbye!")